#ifndef CAMERAPRGMMODES_H
#define CAMERAPRGMMODES_H

#define PRGM_MODE_IDLE -1
#define PRGM_MODE_SINGLE_SHOOT 0
#define PRGM_MODE_SINGLE_SHOOT_BULB 1
#define PRGM_MODE_BURST_SHOOT 2
#define PRGM_MODE_BURST_SHOOT_BULB 3
#define PRGM_MODE_REBURST_SHOOT 4

#endif